(package "vs-dark-theme"
         "1.0"
         "Visual Studio IDE dark theme")

(website-url "https://github.com/emacs-vs/vs-dark-theme")
(keywords "")

(package-file "vs-dark-theme.el")

(source "melpa")

(depends-on "emacs" "24.1")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
